adding documentation for notifyClose best pratices
rabbitmq/amqp091-go pull request #60
Opened 2022-03-31 12:49 UTC by DanielePalaia

Improving the doc describing the behaviour of notifyClose in case of non graceful disconnection.

2022-03-31 13:44 UTC, Gsantomaggio requested changes

2022-03-31 13:44 UTC, Gsantomaggio commented on doc.go
> +go func() {
I would rewrite like:
```golang
for notifyConnClose != nil || notifyChanClose != nil {
 select {
  case err, ok := <-notifyConnClose:
      if !(ok) {
        notifyConnClose = nil
      } else {
        fmt.Printf("connection closed, error %s", err)
      }
    case err, ok := <-notifyChanClose:
      if !(ok) {
        notifyChanClose = nil
      } else {
        fmt.Printf("channel closed, error %s", err)
      }
    }
 }
```

2022-03-31 16:37 UTC, DanielePalaia commented
Ok tested it! It looks good!

2022-04-01 09:18 UTC, Gsantomaggio approved these changes

2022-04-01 09:24 UTC, merged